project:
  type: website
  output-dir: docs

website:
  title: "Chris Talbot"
  navbar:
    search: true
    tools:
      - icon: github
        href: https://www.github.com/chris-a-talbot
      - icon: linkedin
        href: https://www.linkedin.com/in/chris-talbot
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: portfolio.qmd
        text: Portfolio
      - href: https://www.argscape.com
        text: ARGscape
  back-to-top-navigation: true
  page-footer: 
    left: "Copyright 2025, Chris Talbot" 
    right: 
      - icon: github
        href: https://github.com/chris-a-talbot
      - icon: linkedin
        href: https://www.linkedin.com/in/chris-talbot

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

